CREATE TABLE short_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(32) NOT NULL,
    long_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    click_count BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_short_links_code ON short_links (code);
CREATE INDEX idx_short_links_active_expiry ON short_links (active, expires_at);
CREATE INDEX idx_short_links_created_at ON short_links (created_at);
